# Generated by Django 5.0.2 on 2024-08-23 16:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('test_type', models.CharField(choices=[('test1', 'Test 1'), ('test2', 'Test 2')], max_length=10)),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 8, 23))])),
                ('timing', models.TimeField()),
            ],
        ),
    ]
