# Generated by Django 5.0.2 on 2024-09-18 07:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recived', 'Recived')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 9, 18))]),
        ),
    ]
